[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "octosuite-wiki"
authors = [{name = "Richard Mwewa", email = "rly0nheart@duck.com"}]
dynamic = ["version", "description"]
